In [1]:
import pandas as pd
import numpy as np 
from matplotlib import pyplot as plt 
import seaborn as sns 

In [3]:
df = pd.read_csv("incident.csv")

In [4]:
df.head()

Unnamed: 0  incidentstate  active  reassignmentcount  reopencount  \
0           4              7       1                  0            0   
1           5              1       1                  1            0   
2           6              1       1                  1            0   
3           7              1       1                  1            0   
4           8              1       1                  1            0   

   sysmodcount  contacttype  knowledge  upriorityconfirmation  caller_id  ...  \
0            0            3          1                      0       2403  ...   
1            1            3          1                      0       2403  ...   
2            2            3          1                      0       2403  ...   
3            3            3          1                      0       2403  ...   
4            4            3          1                      0       2403  ...   

   opened_at_day  opened_at_month  opened_at_year  opened_at_hr  \
0             29                2            2016             4   
1             29                2            2016             4   
2             29                2            2016             4   
3             29                2            2016             4   
4             29                2            2016             4   

   opened_at_minute  created_at_day  created_at_month  created_at_year  \
0                40              29                 2             2016   
1                40              29                 2             2016   
2                40              29                 2             2016   
3                40              29                 2             2016   
4                40              29                 2             2016   

   created_at_hr  created_at_minute  
0              4                 57  
1              4                 57  
2              4                 57  
3              4                 57  
4              4                 57  

[5 rows x 36 columns]

In [5]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [6]:
df.head()

incidentstate  active  reassignmentcount  reopencount  sysmodcount  \
0              7       1                  0            0            0   
1              1       1                  1            0            1   
2              1       1                  1            0            2   
3              1       1                  1            0            3   
4              1       1                  1            0            4   

   contacttype  knowledge  upriorityconfirmation  caller_id  open_by  ...  \
0            3          1                      0       2403      397  ...   
1            3          1                      0       2403      397  ...   
2            3          1                      0       2403      397  ...   
3            3          1                      0       2403      397  ...   
4            3          1                      0       2403      397  ...   

   opened_at_day  opened_at_month  opened_at_year  opened_at_hr  \
0             29                2            2016             4   
1             29                2            2016             4   
2             29                2            2016             4   
3             29                2            2016             4   
4             29                2            2016             4   

   opened_at_minute  created_at_day  created_at_month  created_at_year  \
0                40              29                 2             2016   
1                40              29                 2             2016   
2                40              29                 2             2016   
3                40              29                 2             2016   
4                40              29                 2             2016   

   created_at_hr  created_at_minute  
0              4                 57  
1              4                 57  
2              4                 57  
3              4                 57  
4              4                 57  

[5 rows x 35 columns]

In [7]:
df.isnull().sum()

incidentstate            0
active                   0
reassignmentcount        0
reopencount              0
sysmodcount              0
contacttype              0
knowledge                0
upriorityconfirmation    0
caller_id                0
open_by                  0
createdby                0
updatedby                0
loc                      0
subbcategory             0
symptom                  0
i_impact                 0
assigned_to              0
categoryy                0
resolved_by              0
assignment_group         0
updated_day              0
updated_month            0
updated_year             0
updated_hr               0
updated_minute           0
opened_at_day            0
opened_at_month          0
opened_at_year           0
opened_at_hr             0
opened_at_minute         0
created_at_day           0
created_at_month         0
created_at_year          0
created_at_hr            0
created_at_minute        0
dtype: int64

In [8]:
X=df.drop("i_impact",axis=1)

In [9]:
X.head()

incidentstate  active  reassignmentcount  reopencount  sysmodcount  \
0              7       1                  0            0            0   
1              1       1                  1            0            1   
2              1       1                  1            0            2   
3              1       1                  1            0            3   
4              1       1                  1            0            4   

   contacttype  knowledge  upriorityconfirmation  caller_id  open_by  ...  \
0            3          1                      0       2403      397  ...   
1            3          1                      0       2403      397  ...   
2            3          1                      0       2403      397  ...   
3            3          1                      0       2403      397  ...   
4            3          1                      0       2403      397  ...   

   opened_at_day  opened_at_month  opened_at_year  opened_at_hr  \
0             29                2            2016             4   
1             29                2            2016             4   
2             29                2            2016             4   
3             29                2            2016             4   
4             29                2            2016             4   

   opened_at_minute  created_at_day  created_at_month  created_at_year  \
0                40              29                 2             2016   
1                40              29                 2             2016   
2                40              29                 2             2016   
3                40              29                 2             2016   
4                40              29                 2             2016   

   created_at_hr  created_at_minute  
0              4                 57  
1              4                 57  
2              4                 57  
3              4                 57  
4              4                 57  

[5 rows x 34 columns]

In [10]:
Y = df['i_impact']

In [11]:
Y.head()

0    2
1    2
2    2
3    2
4    2
Name: i_impact, dtype: int64

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=10)

In [14]:
from imblearn.over_sampling import SMOTE

In [15]:
smote = SMOTE()

In [16]:
X_train_smote, y_train_smote = smote.fit_resample(X_train.astype('float'), y_train)

In [18]:
from collections import Counter
print("Before SMOTE :",Counter(y_train))
print("After SMOTE :",Counter(y_train_smote))

Before SMOTE : Counter({2: 94155, 3: 2647, 1: 2393})
After SMOTE : Counter({2: 94155, 1: 94155, 3: 94155})


# Using the important features which we have obtained after feature selection 
caller_id,open_by,updatedby,createdby,assigned_to,resolved_by,loc,sysmodcount,subbcategory,opened_at_day
##selecting 5-6 features to predict impact of the incident from the obtained top 10 features 

In [47]:
X_train_smote_new= X_train_smote[['open_by','loc','categoryy','caller_id','subbcategory','symptom','createdby','assigned_to','resolved_by','opened_at_day']]
X_test_new= X_test[['open_by','loc','categoryy','caller_id','subbcategory','symptom','createdby','assigned_to','resolved_by','opened_at_day']]

In [48]:
from sklearn.ensemble import RandomForestClassifier
model_rf = RandomForestClassifier(max_depth=27)
model_rf.fit(X_train_smote_new,y_train_smote)


RandomForestClassifier(max_depth=27)

In [49]:
# Predicting the model
y_predict_rf = model_rf.predict(X_test_new)

In [50]:
# Finding accuracy, precision, recall and confusion matrix
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
print(accuracy_score(y_test,y_predict_rf))
print(classification_report(y_test,y_predict_rf))


0.9843812480888199
              precision    recall  f1-score   support

           1       0.81      0.91      0.86      1098
           2       1.00      0.99      0.99     40176
           3       0.79      0.97      0.87      1239

    accuracy                           0.98     42513
   macro avg       0.87      0.95      0.91     42513
weighted avg       0.99      0.98      0.98     42513



In [51]:
confusion_matrix(y_test,y_predict_rf)

array([[  995,    91,    12],
       [  213, 39653,   310],
       [   13,    25,  1201]], dtype=int64)

In [64]:
accuracy_rf = (995+39653+1201)/(42513)*100

In [53]:
# Training the model
from sklearn.tree import DecisionTreeClassifier
model_dtree=DecisionTreeClassifier()
model_dtree.fit(X_train_smote_new,y_train_smote)

DecisionTreeClassifier()

In [54]:
# Predicting the model
y_predict_dtree = model_dtree.predict(X_test_new)

In [55]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_dtree))
print(classification_report(y_test,y_predict_dtree))

0.9837461482370099
              precision    recall  f1-score   support

           1       0.78      0.92      0.84      1098
           2       1.00      0.99      0.99     40176
           3       0.80      0.96      0.87      1239

    accuracy                           0.98     42513
   macro avg       0.86      0.96      0.90     42513
weighted avg       0.99      0.98      0.98     42513



In [56]:
confusion_matrix(y_test,y_predict_dtree )

array([[ 1013,    71,    14],
       [  273, 39617,   286],
       [   14,    33,  1192]], dtype=int64)

In [91]:
accuracy_dtree = (1013+39617+1192)/(42513)*100

In [59]:
# Training the model
from sklearn.neighbors import KNeighborsClassifier
model_knn = KNeighborsClassifier(n_neighbors=12,metric='euclidean') # Maximum accuracy for n=10


In [60]:
model_knn.fit(X_train_smote_new,y_train_smote)

KNeighborsClassifier(metric='euclidean', n_neighbors=12)

In [61]:
# Predicting the model
y_predict_knn = model_knn.predict(X_test_new)

In [62]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_knn))
print(classification_report(y_test,y_predict_knn))

0.907675299320208
              precision    recall  f1-score   support

           1       0.32      0.97      0.48      1098
           2       1.00      0.90      0.95     40176
           3       0.42      0.96      0.59      1239

    accuracy                           0.91     42513
   macro avg       0.58      0.94      0.67     42513
weighted avg       0.96      0.91      0.93     42513



In [63]:
confusion_matrix(y_test,y_predict_knn)

array([[ 1060,    24,    14],
       [ 2233, 36337,  1606],
       [   22,    26,  1191]], dtype=int64)

In [65]:
accuracy_knn = (1060+36337+1191)/(42513)*100

In [66]:
# Training the model
from xgboost import XGBClassifier
model_xgb = XGBClassifier()


In [67]:
model_xgb.fit(X_train_smote_new,y_train_smote)

C:\Users\Anup w\anaconda3\lib\site-packages\xgboost\sklearn.py:892: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[11:57:35] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=8, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [68]:
# Predicting the model
y_predict_xgb = model_xgb.predict(X_test_new)

In [69]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_xgb))
print(classification_report(y_test,y_predict_xgb))

0.9573542210617929
              precision    recall  f1-score   support

           1       0.57      0.85      0.68      1098
           2       0.99      0.96      0.98     40176
           3       0.56      0.91      0.70      1239

    accuracy                           0.96     42513
   macro avg       0.71      0.91      0.79     42513
weighted avg       0.97      0.96      0.96     42513



In [70]:
confusion_matrix(y_test,y_predict_xgb)

array([[  936,   149,    13],
       [  680, 38633,   863],
       [   19,    89,  1131]], dtype=int64)

In [71]:
accuracy_XGB= (936+38633+1131)/(42513)*100

In [72]:
# Training the model
from sklearn.neural_network import MLPClassifier
model_mlp = MLPClassifier()

In [73]:
model_mlp.fit(X_train_smote_new,y_train_smote)

C:\Users\Anup w\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [74]:
# Predicting the model
y_predict_mlp = model_mlp.predict(X_test_new)

In [75]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_mlp))
print(classification_report(y_test,y_predict_mlp))

0.6698656881424505
              precision    recall  f1-score   support

           1       0.08      0.76      0.15      1098
           2       0.99      0.66      0.79     40176
           3       0.18      0.80      0.29      1239

    accuracy                           0.67     42513
   macro avg       0.42      0.74      0.41     42513
weighted avg       0.94      0.67      0.76     42513



In [76]:
confusion_matrix(y_test,y_predict_mlp)

array([[  835,   201,    62],
       [ 8910, 26646,  4620],
       [   91,   151,   997]], dtype=int64)

In [77]:
accuracy_mlp = (835+26646+9987)/(42513)*100

In [78]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [79]:
sgnb = GaussianNB()
smnb = MultinomialNB()

In [80]:
spred_gnb = sgnb.fit(X_train_smote_new,y_train_smote)

In [81]:
# Predicting the model
y_predict_sgnb = spred_gnb.predict(X_test_new)

In [82]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_sgnb))
print(classification_report(y_test,y_predict_sgnb))

0.49403711805800576
              precision    recall  f1-score   support

           1       0.04      0.41      0.07      1098
           2       0.96      0.50      0.66     40176
           3       0.05      0.41      0.09      1239

    accuracy                           0.49     42513
   macro avg       0.35      0.44      0.27     42513
weighted avg       0.91      0.49      0.62     42513



In [83]:
confusion_matrix(y_test,y_predict_sgnb )

array([[  451,   409,   238],
       [11209, 20045,  8922],
       [  292,   440,   507]], dtype=int64)

In [84]:
accuracy_gnb = (451+20045+507)/(42513)*100

In [85]:
spred_mnb = smnb.fit(X_train_smote_new,y_train_smote)

In [86]:
# Predicting the model
y_predict_smnb = spred_mnb.predict(X_test_new)

In [87]:
# Finding accuracy, precision, recall and confusion matrix
print(accuracy_score(y_test,y_predict_smnb))
print(classification_report(y_test,y_predict_smnb))

0.49714205066685485
              precision    recall  f1-score   support

           1       0.04      0.14      0.06      1098
           2       0.96      0.50      0.66     40176
           3       0.04      0.58      0.08      1239

    accuracy                           0.50     42513
   macro avg       0.35      0.41      0.27     42513
weighted avg       0.91      0.50      0.63     42513



In [88]:
confusion_matrix(y_test,y_predict_smnb)

array([[  152,   454,   492],
       [ 3876, 20259, 16041],
       [  132,   383,   724]], dtype=int64)

In [89]:
accuracy_mnb =(152+20259+724)/(42513)*100

In [92]:
data = {"MODEL":pd.Series(["model_rf","model_dtree","model_knn","model_xgb","model_mlp","spred_gnb ","spred_mnb"]),
        "Accuracy":pd.Series([accuracy_rf,accuracy_dtree,accuracy_knn,accuracy_XGB,accuracy_mlp,accuracy_gnb,accuracy_mnb])}
table=pd.DataFrame(data)
table 

MODEL   Accuracy
0     model_rf  98.438125
1  model_dtree  98.374615
2    model_knn  90.767530
3    model_xgb  95.735422
4    model_mlp  88.133042
5   spred_gnb   49.403712
6    spred_mnb  49.714205